
----------------------------------------------

SELECT DISTINCT STARNAME
FROM STARSIN, MOVIESTAR
WHERE STARSIN.STARNAME = MOVIESTAR.NAME
AND MOVIETITLE = 'The Usual Suspects'
AND GENDER = 'M';

----------------------------------------------

SELECT DISTINCT STARNAME
FROM STARSIN, MOVIE
WHERE STARSIN.MOVIETITLE = MOVIE.TITLE
AND STUDIONAME = 'MGM'
AND MOVIE.YEAR = 1995

----------------------------------------------

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC, MOVIE
WHERE MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
AND MOVIE.STUDIONAME = 'MGM'

----------------------------------------------

SELECT DISTINCT MOVIE.TITLE
FROM MOVIE
WHERE MOVIE.LENGTH > (
    SELECT LENGTH 
    FROM MOVIE 
    WHERE TITLE = 'Star Wars'
);

----------------------------------------------

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC
WHERE MOVIEEXEC.NETWORTH > (
	SELECT NETWORTH
	FROM MOVIEEXEC
	WHERE NAME = 'Stephen Spielberg'
);
