
-------------------------------------------

SELECT SHIPS.NAME
FROM SHIPS, CLASSES
WHERE SHIPS.CLASS = CLASSES.CLASS
AND CLASSES.DISPLACEMENT > 50000

-------------------------------------------

SELECT DISTINCT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS, CLASSES, BATTLES, OUTCOMES
WHERE BATTLES.NAME='Guadalcanal'
AND CLASSES.CLASS = SHIPS.CLASS
AND OUTCOMES.BATTLE = BATTLES.NAME
AND SHIPS.NAME = OUTCOMES.SHIP

-------------------------------------------

SELECT DISTINCT C1.COUNTRY
FROM CLASSES AS C1, CLASSES AS C2
WHERE C1.COUNTRY = C2.COUNTRY
AND C1.TYPE != C2.TYPE

-------------------------------------------

SELECT DISTINCT SHIPS.NAME
FROM SHIPS, BATTLES AS B1, BATTLES AS B2, 
OUTCOMES AS O1, OUTCOMES AS O2
WHERE SHIPS.NAME = O1.SHIP
AND SHIPS.NAME = O2.SHIP
AND O1.BATTLE = B1.NAME
AND O2.BATTLE = B2.NAME
AND B1.DATE < B2.DATE
AND O1.RESULT = 'damaged'

-------------------------------------------