SELECT CLASS, COUNTRY 
FROM CLASSES
WHERE NUMGUNS < 10;

SELECT SHIPS.NAME AS 'shipNAME'
FROM SHIPS
WHERE LAUNCHED < 1918;

SELECT SHIP, BATTLE
FROM OUTCOMES
WHERE RESULT='sunk'

SELECT SHIPS.NAME
FROM SHIPS
WHERE SHIPS.NAME=CLASS;

SELECT SHIPS.NAME
FROM SHIPS
WHERE SHIPS.NAME LIKE 'r%';

SELECT SHIPS.NAME
FROM SHIPS
WHERE SHIPS.NAME LIKE '_% _%'