
INSERT INTO MOVIESTAR(NAME, BIRTHDATE)
VALUES('Nicole Kidman', 1967-06-20)

SELECT * FROM MOVIESTAR
	
--------------------------------------------

DELETE FROM MOVIEEXEC
WHERE NETWORTH > 30000000

SELECT * FROM MOVIEEXEC

-------------------------------------------

DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL

SELECT * FROM MOVIESTAR