
------------------------------------------------

SELECT DISTINCT MOVIE.TITLE, MOVIEEXEC.NAME
FROM MOVIE 
JOIN MOVIEEXEC
  ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
WHERE MOVIEEXEC.CERT# IN (
    SELECT MOVIE.PRODUCERC#
    FROM MOVIE
    WHERE TITLE = 'STAR WARS'
);

------------------------------------------------

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC 
JOIN MOVIE
  ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
JOIN STARSIN 
  ON MOVIE.TITLE = STARSIN.MOVIETITLE
WHERE STARSIN.STARNAME = 'HARRISON FORD'

------------------------------------------------

SELECT DISTINCT MOVIE.STUDIONAME, STARSIN.STARNAME
FROM MOVIE
JOIN STARSIN
	ON MOVIE.TITLE = STARSIN.MOVIETITLE
ORDER BY STUDIONAME

------------------------------------------------

SELECT DISTINCT STARSIN.STARNAME, MOVIEEXEC.NETWORTH, STARSIN.MOVIETITLE
FROM MOVIE
JOIN STARSIN
	ON STARSIN.MOVIETITLE = MOVIE.TITLE
JOIN MOVIEEXEC
	ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE MOVIEEXEC.NETWORTH >= ALL(
	SELECT MOVIEEXEC.NETWORTH
	FROM MOVIEEXEC
) ORDER BY STARSIN.MOVIETITLE;

------------------------------------------------

SELECT MOVIESTAR.NAME, STARSIN.MOVIETITLE
FROM MOVIESTAR
LEFT JOIN STARSIN 
	ON MOVIESTAR.NAME = STARSIN.STARNAME
WHERE STARSIN.MOVIETITLE IS NULL;