
------------------------------------

SELECT DISTINCT PRODUCT.MAKER
FROM PRODUCT
WHERE PRODUCT.MODEL IN (
	SELECT MODEL
	FROM PC
	WHERE SPEED > 500
);

------------------------------------

SELECT PRINTER.CODE, PRINTER.MODEL, PRINTER.PRICE
FROM PRINTER
WHERE PRICE = (
	SELECT MAX(PRINTER.PRICE)
	FROM PRINTER
);

------------------------------------

SELECT *
FROM LAPTOP
WHERE LAPTOP.SPEED < (
	SELECT MIN(PC.SPEED)
	FROM PC
);

------------------------------------

SELECT TOP 1 MODEL, PRICE
FROM (
	SELECT MODEL, PRICE FROM PC
	UNION
	SELECT MODEL, PRICE FROM LAPTOP
	UNION
	SELECT MODEL, PRICE FROM PRINTER
) AS ALL_PRODUCTS ORDER BY PRICE DESC

------------------------------------

SELECT TOP 1 PRODUCT.MAKER
FROM PRODUCT, PRINTER
WHERE PRODUCT.MODEL = PRINTER.MODEL
AND PRINTER.COLOR = 'y'
ORDER BY PRICE ASC

------------------------------------

SELECT DISTINCT MAKER
FROM PRODUCT 
WHERE PRODUCT.MODEL IN (
    SELECT P.MODEL
    FROM PC AS P
    WHERE P.SPEED = (
        SELECT TOP 1 C.SPEED
        FROM PC AS C
        WHERE C.RAM = (SELECT MIN(RAM) FROM PC)
        ORDER BY C.SPEED DESC
    )
);