
------------------------------------

SELECT DISTINCT CLASSES.COUNTRY
FROM CLASSES
WHERE CLASSES.NUMGUNS = (
	SELECT MAX(CLASSES.NUMGUNS)
	FROM CLASSES
);

------------------------------------

SELECT CLASSES.CLASS
FROM CLASSES
WHERE CLASS IN ( 
	SELECT CLASS
	FROM SHIPS, OUTCOMES
	WHERE SHIPS.NAME = OUTCOMES.SHIP
	AND OUTCOMES.RESULT = 'SUNK'
);

------------------------------------

SELECT SHIPS.NAME, SHIPS.CLASS
FROM SHIPS
WHERE SHIPS.CLASS IN (
	SELECT CLASSES.CLASS
	FROM CLASSES
	WHERE CLASSES.BORE = 16
);

------------------------------------

SELECT OUTCOMES.BATTLE
FROM OUTCOMES
WHERE OUTCOMES.SHIP IN (
	SELECT SHIPS.NAME
	FROM SHIPS
	WHERE SHIPS.CLASS = 'KONGO'
);

------------------------------------

SELECT SHIPS.CLASS, SHIPS.NAME
FROM SHIPS, CLASSES AS C1
WHERE SHIPS.CLASS = C1.CLASS
AND C1.NUMGUNS >= ALL(
	SELECT NUMGUNS
	FROM CLASSES AS C2
	WHERE C2.BORE = C1.BORE
) ORDER BY C1.CLASS