
-----------------------------------------------

SELECT MOVIE.TITLE, MOVIE.YEAR, MOVIE.LENGTH
FROM MOVIE
WHERE MOVIE.LENGTH > 120 OR MOVIE.LENGTH IS NULL
AND MOVIE.YEAR < 2000;

-----------------------------------------------

SELECT MOVIESTAR.NAME, MOVIESTAR.GENDER
FROM MOVIESTAR
WHERE MOVIESTAR.BIRTHDATE > 1948
AND MOVIESTAR.NAME LIKE 'J%'
ORDER BY MOVIESTAR.NAME DESC;

-----------------------------------------------

SELECT STUDIO.NAME, COUNT(DISTINCT STARNAME) AS num_actors
FROM STUDIO
	JOIN MOVIE ON STUDIO.NAME = MOVIE.STUDIONAME
	JOIN STARSIN ON STARSIN.MOVIETITLE = MOVIE.TITLE
GROUP BY STUDIO.NAME;

-----------------------------------------------

SELECT MOVIESTAR.NAME, COUNT(STARSIN.MOVIETITLE) as num_movies
FROM MOVIESTAR
LEFT JOIN STARSIN ON MOVIESTAR.NAME = STARSIN.STARNAME
GROUP BY MOVIESTAR.NAME;

-----------------------------------------------

SELECT M1.STUDIONAME, M1.TITLE, M1.YEAR
FROM MOVIE AS M1
WHERE M1.YEAR = (
	SELECT MAX(M2.YEAR)
	FROM MOVIE M2
	WHERE M2.STUDIONAME = M1.STUDIONAME
);

-----------------------------------------------

SELECT MOVIESTAR.NAME
FROM MOVIESTAR 
WHERE MOVIESTAR.GENDER = 'M'
AND MOVIESTAR.BIRTHDATE = (
	SELECT MAX(MOVIESTAR.BIRTHDATE)
	FROM MOVIESTAR
	WHERE GENDER = 'M'
);

-----------------------------------------------

SELECT STUDIO.NAME, STARSIN.STARNAME, COUNT(MOVIE.TITLE) as num_movies
FROM STUDIO
JOIN MOVIE ON STUDIO.NAME = MOVIE.STUDIONAME
JOIN STARSIN ON MOVIE.TITLE = STARSIN.MOVIETITLE
GROUP BY STUDIO.NAME, STARSIN.STARNAME
HAVING COUNT(MOVIE.TITLE) = (
	SELECT MAX(movie_count)
	FROM (
		SELECT STUDIO.NAME, STARSIN.STARNAME, COUNT(MOVIE.TITLE) as movie_count
		FROM STUDIO
		JOIN MOVIE ON STUDIO.NAME = MOVIE.STUDIONAME
		JOIN STARSIN ON MOVIE.TITLE = STARSIN.MOVIETITLE
		GROUP BY STUDIO.NAME, STARSIN.STARNAME
	) AS T
WHERE T.NAME = STUDIO.NAME
);

-----------------------------------------------

SELECT STARSIN.MOVIETITLE, STARSIN.MOVIEYEAR, COUNT(STARSIN.STARNAME)
FROM STARSIN
GROUP BY STARSIN.MOVIETITLE, STARSIN.MOVIEYEAR
HAVING COUNT(STARSIN.STARNAME) > 2;

