
-----------------------------------------------------

SELECT LAPTOP.MODEL, LAPTOP.CODE, LAPTOP.SCREEN
FROM LAPTOP
WHERE LAPTOP.SCREEN = 11 

UNION

SELECT LAPTOP.MODEL, LAPTOP.CODE, LAPTOP.SCREEN
FROM LAPTOP
WHERE LAPTOP.SCREEN = 15;

-----------------------------------------------------

SELECT DISTINCT PC.MODEL
FROM PC
JOIN PRODUCT P1 ON PC.MODEL = P1.MODEL
WHERE PC.PRICE < (
	SELECT MIN(LAPTOP.PRICE)
	FROM LAPTOP
	JOIN PRODUCT P2 ON LAPTOP.MODEL = P2.MODEL
	WHERE P1.MAKER = P2.MAKER
);

-----------------------------------------------------

SELECT PC.MODEL, CONVERT(DECIMAL(9, 2), AVG(PC.PRICE)) as avg_price
FROM PC
JOIN PRODUCT P1 ON PC.MODEL = P1.MODEL
GROUP BY PC.MODEL, P1.MAKER
HAVING AVG(PC.PRICE) < (
	SELECT MIN(LAPTOP.PRICE)
	FROM LAPTOP
	JOIN PRODUCT P2 ON LAPTOP.MODEL = P2.MODEL
	WHERE P1.MAKER = P2.MAKER
);

-----------------------------------------------------

SELECT PC1.CODE, PRODUCT.MAKER, 
       (SELECT COUNT(*) 
        FROM PC PC2 
        WHERE PC2.PRICE >= PC1.PRICE) AS num_pc_higher_price
FROM PC AS PC1 
JOIN PRODUCT ON PC1.MODEL = PRODUCT.MODEL
ORDER BY PC1.CODE;
