
---------------------------------------------------

SELECT DISTINCT OUTCOMES.SHIP 
FROM OUTCOMES
WHERE OUTCOMES.SHIP LIKE 'C%' OR OUTCOMES.SHIP LIKE 'K%'

---------------------------------------------------

SELECT DISTINCT SHIPS.NAME, CLASSES.COUNTRY
FROM SHIPS
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
LEFT JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT != 'SUNK' OR RESULT IS NULL

---------------------------------------------------

SELECT CLASSES.COUNTRY, COUNT(OUTCOMES.SHIP)
FROM CLASSES
LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'SUNK' OR OUTCOMES.RESULT IS NULL
GROUP BY CLASSES.COUNTRY;

---------------------------------------------------

SELECT OUTCOMES.BATTLE
FROM OUTCOMES
GROUP BY OUTCOMES.BATTLE
HAVING COUNT(OUTCOMES.SHIP) > (
	SELECT COUNT(SHIP)
	FROM OUTCOMES
	WHERE OUTCOMES.BATTLE = 'Guadalcanal'
	GROUP BY OUTCOMES.BATTLE
);

---------------------------------------------------

SELECT OUTCOMES.BATTLE
FROM OUTCOMES
JOIN SHIPS ON OUTCOMES.SHIP = SHIPS.NAME
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
GROUP BY OUTCOMES.BATTLE
HAVING COUNT(CLASSES.COUNTRY) > (
	SELECT COUNT(CLASSES.COUNTRY)
	FROM OUTCOMES
	JOIN SHIPS ON OUTCOMES.SHIP = SHIPS.NAME
    JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
    WHERE OUTCOMES.BATTLE = 'Surigao Strait'
    GROUP BY OUTCOMES.BATTLE
);

---------------------------------------------------

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE CLASSES.DISPLACEMENT <= ALL (
	SELECT CLASSES.DISPLACEMENT
	FROM CLASSES
	JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS
)
AND CLASSES.DISPLACEMENT >= ALL (
	SELECT CLASSES.NUMGUNS
	FROM CLASSES
	JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS
);

---------------------------------------------------

SELECT COUNT(DISTINCT o1.SHIP) AS num_ships
FROM OUTCOMES o1
JOIN OUTCOMES o2 ON o1.SHIP = o2.SHIP
WHERE o1.RESULT = 'damaged'
AND o2.RESULT = 'ok';

---------------------------------------------------

SELECT O.SHIP
FROM OUTCOMES AS O
JOIN BATTLES AS B ON O.BATTLE = B.NAME
GROUP BY O.SHIP, O.RESULT, B.DATE
HAVING O.RESULT = 'ok'
AND B.DATE > ( 
	SELECT BATTLES.DATE
	FROM OUTCOMES
	JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
	WHERE OUTCOMES.SHIP = O.SHIP
	GROUP BY OUTCOMES.SHIP, OUTCOMES.RESULT, BATTLES.DATE
	HAVING OUTCOMES.RESULT = 'damaged'
)
AND COUNT(O.SHIP) >= (
		SELECT COUNT(OUTCOMES.SHIP)
		FROM OUTCOMES 
		JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
		WHERE OUTCOMES.SHIP = O.SHIP
		GROUP BY OUTCOMES.BATTLE, OUTCOMES.RESULT, BATTLES.DATE
		HAVING OUTCOMES.RESULT = 'damaged'
);
