
---------------------------------------------

SELECT CONVERT(DECIMAL(9, 2), AVG(PC.SPEED)) AS AvgSpeed 
FROM PC;

---------------------------------------------

SELECT PRODUCT.MAKER, CONVERT(DECIMAL(9, 2), AVG(LAPTOP.SCREEN)) as AvgScreen
FROM PRODUCT, LAPTOP
WHERE PRODUCT.MODEL = LAPTOP.MODEL
GROUP BY PRODUCT.MAKER;

---------------------------------------------

SELECT CONVERT(DECIMAL(9, 2), AVG(LAPTOP.SPEED)) as AvgSpeed
FROM LAPTOP
WHERE LAPTOP.PRICE > 1000

---------------------------------------------

SELECT PRODUCT.MAKER, CONVERT(DECIMAL(9, 2), AVG(PC.PRICE)) as AvgPrice
FROM PRODUCT, PC
WHERE PRODUCT.MODEL = PC.MODEL
AND PRODUCT.MAKER = 'A'
GROUP BY PRODUCT.MAKER;

---------------------------------------------

SELECT T.MAKER, CONVERT(DECIMAL(9, 2), AVG(T.PRICE)) as AvgPrice
FROM (
	SELECT PRODUCT.MAKER, PC.PRICE
	FROM PRODUCT, PC
	WHERE PRODUCT.MODEL = PC.MODEL 
	AND PRODUCT.MAKER = 'B'

	UNION ALL

	SELECT PRODUCT.MAKER, LAPTOP.PRICE
	FROM PRODUCT, LAPTOP
	WHERE PRODUCT.MODEL = LAPTOP.MODEL
	AND PRODUCT.MAKER = 'B'
) T
GROUP BY T.MAKER;

---------------------------------------------

SELECT PC.SPEED, CONVERT(DECIMAL(9, 2), AVG(PC.PRICE)) AS AvgPrice
FROM PC
GROUP BY PC.SPEED;

---------------------------------------------

SELECT PRODUCT.MAKER, COUNT(PC.MODEL) AS CNT
FROM PRODUCT, PC
WHERE PRODUCT.MODEL = PC.MODEL
AND PRODUCT.TYPE = 'PC'
GROUP BY PRODUCT.MAKER
HAVING COUNT(PC.MODEL) >= 3;

---------------------------------------------

SELECT PRODUCT.MAKER, MAX(PC.PRICE) AS PRICE
FROM PRODUCT, PC
WHERE PRODUCT.MODEL = PC.MODEL
AND PRODUCT.TYPE = 'PC'
GROUP BY PRODUCT.MAKER
HAVING MAX(PC.PRICE) = (
	SELECT MAX(PC2.PRICE)
	FROM PRODUCT, PC AS PC2
	WHERE PRODUCT.MODEL = PC2.MODEL
	AND PRODUCT.TYPE = 'PC'
);

---------------------------------------------

SELECT PC.SPEED, CONVERT(DECIMAL(9, 2), AVG(PC.PRICE)) as AvgPrice
FROM PC
GROUP BY PC.SPEED
HAVING PC.SPEED >= 800;

---------------------------------------------

SELECT CONVERT(DECIMAL(9, 2), AVG(PC.HD)) as AvgHDD
FROM PRODUCT, PC
WHERE PRODUCT.MODEL = PC.MODEL
AND PRODUCT.MAKER IN (
	SELECT DISTINCT MAKER
	FROM PRODUCT
	WHERE PRODUCT.TYPE = 'PRINTER'
);
