
-------------------------------------------

SELECT COUNT(CLASSES.CLASS) AS classNum
FROM CLASSES

-------------------------------------------

SELECT CLASSES.CLASS, AVG(CLASSES.NUMGUNS) AS avgGuns
FROM CLASSES
GROUP BY CLASS;

-------------------------------------------

SELECT AVG(CLASSES.NUMGUNS) AS avgGuns
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS;

-------------------------------------------

SELECT CLASSES.CLASS, MIN(SHIPS.LAUNCHED), MAX(SHIPS.LAUNCHED)
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS
GROUP BY CLASSES.CLASS
ORDER BY CLASSES.CLASS;

-------------------------------------------

SELECT SHIPS.CLASS, COUNT(OUTCOMES.SHIP) AS sunkShipNum
FROM SHIPS, OUTCOMES
WHERE SHIPS.NAME = OUTCOMES.SHIP
AND OUTCOMES.RESULT = 'SUNK'
GROUP BY SHIPS.CLASS;

-------------------------------------------

SELECT CLASSES.CLASS, COUNT(SHIPS.NAME)
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
WHERE OUTCOMES.RESULT='sunk'
GROUP BY CLASSES.CLASS
HAVING CLASSES.CLASS IN (
  SELECT CLASSES.CLASS 
  FROM CLASSES 
  JOIN SHIPS 
    ON CLASSES.CLASS=SHIPS.CLASS 
  GROUP BY CLASSES.CLASS 
  HAVING COUNT(SHIPS.NAME) > 2
);

-------------------------------------------

SELECT CLASSES.COUNTRY, CONVERT(DECIMAL(9,2), AVG(CLASSES.BORE)) as avg_displacement
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS
GROUP BY CLASSES.COUNTRY;
